### ISSUE TITLE
Syntax in the English lang file not supported by AMOS

### ISSUE THREAD

**Issue by mudrd8mz** [jcastello46/moodle-mod_unedtrivial#1]
Strings congratulations1 and congratulations2 do not follow https://docs.moodle.org/dev/Plugin_contribution_checklist#Strings and contain string concatenation, not supported by the AMOS parser.

As a consequence, this plugin's strings have not been registered with lang.moodle.org for community translation.

**Comment by jcastello46** [comment]
Concatenation deleted from EN translation.
Thanks for your message.

**Comment by germanvaleroelizondo** [comment]
Hi,
Even though the strings here in GitHub are fixed, the file hosted at the Moodle plugins database is the old version and AMOS does not have the strings available for translation.
Please update the files hosted at the Moodle plugins database.

PS: Please update also the SPANISH language strings, as I will be uploading them to the international spanish and mexican spanish language packs as soon as the english strings are hosted in AMOS.

You are supposed to release a new version in the plugins directory and use the button "Request re-approval" at the Developer zone tab. Please refer to https://docs.moodle.org/dev/Plugin_contribution#Sharing_code_in_the_Plugins_directory for details. Thanks.

Felicitaciones por este nuevo plugin.

**Comment by jcastello46** [comment]
Hello @germanvaleroelizondo 
Plugin has been updated in Moodle too. I have checked that english strings are now available from AMOS and I have uploaded ES file too. Now it's under revision.
Gracias!

**Comment by mudrd8mz** [comment]
Please note. It works best if only English files ship with the plugin code, and all other translations (including your actual mother tongue) is processed via AMOS. If a translation exists in both plugin and AMOS, keeping them in sync is an extra work to be done by you and the lang pack maintainer. Thanks for understanding.

**Comment by germanvaleroelizondo** [comment]
Hi,

Thanks for updating the plugin English and Spanish language files.

As David Mudrak has written, it is best if you ONLY include the English language files in the Moodle plugins download database. But, in this case, it was EXCELLENT that you (a native Spanish speaker), have also included here in GitHub an ES language strings file. GRACIAS.

I have sent your ES strings to the international Spanish language pack maintainers at AMOS and I have uploaded the same strings (with a few minor changes) into the es_mx language pack.

As soon as the ES language pack maintainers confirm that they have uploaded the strings into the ES language pack, you could safely delete the ES strings from here. Please note that the ES language pack maintainers often change the author's strings in order to match the ES language preferred style and grammar. Some authors are happy about this, others not so. 

As I have changed some of your original ES strings for the es_mx language pack, II will consider all reasonable changes requested by a plugin author, as all translators are only humans and we make mistakes that somebody else might detect.

The es_mx language pack has some differences from the ES language pack, to make it more understandable for mexican users (eg, we use PCs instead of Ordenadores, I use Email instead of e-mail,...).

Thanks for your help and congratulations on this new plugin.
